export type MatchSummaryData = {
  outcome: {
    headline: string;
    key_stats: { label: string; value: string; source_field: string }[];
    standout_performers: { player: string; team: string; reason: string; source_field: string }[];
  };
  tactics: { prose: string };
  metadata: {
    match_id: number;
    home_team: string;
    away_team: string;
    competition: string;
    match_label: string;
    model: string;
  };
};

// Disclaimer text is hardcoded to match 3943043's specific known issues,
// found by the manual per-claim trace in football-analytics'
// docs/specs/match-summary/VERIFICATION-3943043.md: an off-ball/on-ball
// centroid mislabel, the resulting backwards spatial comparison, and a
// false hull-membership claim about a player. If this component is ever
// reused for a different match's match_summary.json, this list must be
// revisited — it is not a generic "AI-generated, may contain errors"
// notice, and is only accurate for the one match it was written against.
const DISCLAIMER_ISSUES = [
  "The prose labels Spain's and England's shape centroids as \"on-ball\" — they are actually off-ball (out-of-possession) centroids from team_shape_spain.json/team_shape_england.json. The coordinate values are copied correctly; only the on-ball/off-ball label is wrong.",
  "Because of that mislabel, the claim that England sat more central than Spain is backwards: pitch center is y=40, and England's cited y (39.2) is actually closer to center than Spain's (41.4).",
  "The prose describes England's first-half possession hull as running \"through Stones and Guehi.\" Guehi is a real hull vertex, but Stones is not — his position places him inside the shape, not on its boundary.",
];

/** Section eyebrow label — matches ComponentModal.tsx's sidebar section-label convention. */
function SectionLabel({ children }: { children: React.ReactNode }) {
  return (
    <div className="mb-2 font-mono text-mono-sm tracking-[0.1em] text-faint uppercase">
      {children}
    </div>
  );
}

export function MatchSummaryContent({ data }: { data: MatchSummaryData }) {
  const paragraphs = data.tactics.prose.split("\n\n").filter((p) => p.length > 0);

  return (
    <div>
      <div className="mb-6 rounded-lg border border-focal border-l-4 bg-focal-soft p-4 text-sm leading-relaxed break-words text-text">
        <div className="mb-2 font-mono text-mono-sm font-semibold tracking-[0.04em] text-focal uppercase">
          ⚠ AI-generated summary — verified issues below
        </div>
        <p className="mb-2.5">
          This summary was generated by an LLM from structured match data and manually
          verified once. The structured stats and performers below (12 of 12 claims) were
          verified exactly correct. The tactics paragraphs below (11 of 15 claims fully
          grounded) contain three known issues, left uncorrected on purpose:
        </p>
        <ul className="mb-2.5 list-disc space-y-1.5 pl-5">
          {DISCLAIMER_ISSUES.map((issue) => (
            <li key={issue}>{issue}</li>
          ))}
        </ul>
        <p className="text-muted">
          No automated evaluation exists yet for this feature — that&apos;s Module 3 of the
          curriculum, not built here. Full claim-by-claim trace:{" "}
          docs/specs/match-summary/VERIFICATION-3943043.md.
        </p>
      </div>

      <h2 className="display mb-5 text-display-4 font-semibold text-text">{data.outcome.headline}</h2>

      <div className="mb-6 grid grid-cols-2 gap-2.5 sm:grid-cols-4">
        {data.outcome.key_stats.map((stat) => (
          <div
            key={stat.label}
            title={stat.source_field}
            className="rounded-lg border border-border p-2.5"
          >
            <div className="mb-1 font-mono text-mono-xs tracking-[0.04em] text-faint uppercase">
              {stat.label}
            </div>
            <div className="text-base font-semibold text-text">{stat.value}</div>
          </div>
        ))}
      </div>

      <div className="mb-6">
        <SectionLabel>Standout performers</SectionLabel>
        {data.outcome.standout_performers.map((performer) => (
          <div
            key={performer.player}
            title={performer.source_field}
            className="border-b border-border py-2 last:border-b-0"
          >
            <span className="font-semibold text-text">{performer.player}</span>{" "}
            <span className="font-mono text-mono-sm text-muted">({performer.team})</span>
            <div className="mt-0.5 text-sm text-muted">{performer.reason}</div>
          </div>
        ))}
      </div>

      <div className="mb-5">
        <SectionLabel>Tactics</SectionLabel>
        {paragraphs.map((paragraph, i) => (
          <p key={i} className="mb-3 text-sm leading-relaxed text-text last:mb-0">
            {paragraph}
          </p>
        ))}
      </div>

      <div className="font-mono text-mono-xs text-faint">
        {data.metadata.match_label} · {data.metadata.competition} · model: {data.metadata.model}
      </div>
    </div>
  );
}
